import React,{useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {ArrowRight,ChevronDown,Menu,Search,ShoppingBag,X,ShieldCheck,Truck,RefreshCcw} from 'lucide-react'
import './styles.css'

const site={domain:'skyeyehome.com',adminPath:'/#/admin'}
const adminCredentials={username:'admin@skyeyehome.com',password:'SkyeyeHome2026!'}
const company={name:'Hong Kong AnxinTrading Co Limited',email:'ajnpay@outlook.com',phone:'+852 62315668',address:'HONGKONG ANXUNTRATION CO., LIMITED'}
const categories=[
 {name:'Kitchen Systems',note:'Order in, cook calmly',items:['Stock Pot','Saucepan','Food Storage Box','Pantry Jar','Rice Storage Bin','Spice Bottle Set','Countertop Shelf','Dish Rack','Utensil Holder','Lunch Container']},
 {name:'Storage Studio',note:'A place for every useful thing',items:['Lidded Storage Box','Under-bed Case','Stackable Closet Bin','Foldable Laundry Basket','Toy Organizer','Shoe Storage Bench','Utility Cart','Pegboard Organizer','Garment Rack','Drawer Tower']},
 {name:'Furniture Edit',note:'Everyday pieces, considered',items:['Mesh Office Chair','Gaming Chair','Platform Bed','Side Table','Folding Chair','Bedside Table','Five-tier Rack','Shoe Cabinet','Writing Desk','Plant Stand']},
 {name:'Soft & Bath',note:'Small rituals, softer rooms',items:['Toilet Brush','Shower Shelf','Bath Mat','Nap Blanket','Throw Pillow','Lumbar Cushion','Blackout Curtain','Microfiber Curtain','Laundry Hamper','Over-toilet Organizer']}
]
const prices=[34,28,22,19,89,24,49,39,18,21,32,46,27,35,74,109,65,42,129,69,119,189,78,59,85,42,139,229,99,119,29,159,22,36,25,31,44,27,58,51]
const products=categories.flatMap((cat,ci)=>cat.items.map((name,i)=>({id:ci*10+i+1,name,category:cat.name,price:prices[ci*10+i],image:`/products/product-${String(ci*10+i+1).padStart(2,'0')}.webp`,description:'Designed for dependable daily use, with a quiet footprint and durable materials.'})))
const terms=['Agreement','Eligibility','Product information','Prices and taxes','Orders','Payment','Shipping','Delivery windows','Risk of loss','Returns','Refunds','Cancellations','Intellectual property','User content','Privacy','Limitation of liability','Governing law']
const policyLabels=['About us','Payment','Returns & refunds','Cancellation policy','Shipping policy','Order tracking','Terms of Service · 17 parts','Privacy policy','DMCA']
const policyContent={
 'About us':`Skyeyehome is an online home-living storefront operated by ${company.name}. We curate durable, practical goods for kitchens, storage, furniture, bathrooms and everyday comfort. Our customer-service contact is ${company.email}.`,
 'Payment':`Orders are paid at checkout using the payment method selected by the customer. Available options are PayPal, Visa and credit or debit card. An order is accepted only after payment authorization. This preview currently demonstrates the interface; production payment requires a connected merchant account.`,
 'Returns & refunds':'You may request a return within 30 calendar days after delivery. Items must be unused, clean, complete and packed safely. Contact us before sending anything back. Approved refunds are issued to the original payment method after inspection; original shipping charges are non-refundable unless the item arrived damaged or incorrect.',
 'Cancellation policy':'Cancellation requests should be sent to tianyanhome@outlook.com as soon as possible. Orders can normally be cancelled before dispatch. Once dispatched, the order follows the returns process. Any refund timing depends on the payment provider.',
 'Shipping policy':'Orders are prepared during business days. Dispatch confirmation and available tracking details are sent to the email used at checkout. Delivery estimates vary by destination, customs and carrier conditions. Customers are responsible for accurate delivery details and any applicable import charges.',
 'Order tracking':'Use the tracking reference in your dispatch email on the carrier website. If tracking has not updated for seven business days, contact tianyanhome@outlook.com with the order reference and delivery address so we can investigate.',
 'Privacy policy':`We use order and contact information only to process purchases, provide support, prevent fraud and meet legal obligations. We do not claim to sell personal data. Requests about personal information can be sent to ${company.email}. Please do not send payment-card details by email.`,
 'DMCA':'If you believe material on skyeyehome.com infringes your copyright, send a notice to tianyanhome@outlook.com identifying the copyrighted work, the material and its location, your contact details, a good-faith statement and your signature. We will review complete notices and respond as required by applicable law.'
}

function App(){
 const [cat,setCat]=useState('All'); const [cart,setCart]=useState([]); const [drawer,setDrawer]=useState(false); const [page,setPage]=useState(()=>location.hash==='#/admin'?'admin':'home'); const [query,setQuery]=useState('');
 const visible=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[cat,query])
 const add=p=>{setCart(c=>[...c,p]);setDrawer(true)}
 const buy=p=>{setCart(c=>[...c,p]);setDrawer(false);setPage('checkout');window.scrollTo(0,0)}
 if(page==='checkout') return <Checkout cart={cart} onBack={()=>setPage('home')}/>
 if(page==='info') return <Info onBack={()=>setPage('home')}/>
 if(page==='admin') return localStorage.getItem('skyeye-admin-auth')==='true'?<Admin onBack={()=>setPage('home')}/>:<AdminLogin onBack={()=>setPage('home')} onLogin={()=>{localStorage.setItem('skyeye-admin-auth','true');setPage('admin')}}/>
 return <><header><a className="logo" onClick={()=>{setPage('home');setCat('All')}}>SKYEYE<span>HOME</span></a><nav>{categories.map(c=><button key={c.name} onClick={()=>{setCat(c.name);document.querySelector('#catalog')?.scrollIntoView({behavior:'smooth'})}}>{c.name}</button>)}</nav><div className="tools"><label><Search size={16}/><input placeholder="Search pieces" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="bag" onClick={()=>setDrawer(true)}><ShoppingBag size={18}/><b>{cart.length}</b></button><button className="menu"><Menu size={20}/></button></div></header>
 <main><section className="hero"><div className="hero-copy"><p className="eyebrow">A QUIETER WAY TO LIVE WELL / 2026</p><h1>Good objects.<br/><em>Better rhythms.</em></h1><p className="lede">Functional home goods with a point of view — chosen for the spaces where real life happens.</p><button className="primary" onClick={()=>document.querySelector('#catalog')?.scrollIntoView({behavior:'smooth'})}>Explore the edit <ArrowRight size={16}/></button></div><div className="hero-art"><div className="art-stamp">USEFUL<br/><span>EVERYDAY</span></div><div className="art-card card-one">01<br/><strong>ROOM<br/>TO BREATHE</strong></div><div className="art-card card-two">FORM<br/><strong>FOLLOWS<br/>FUNCTION</strong></div></div></section>
 <section className="signals"><div><Truck/>Thoughtful dispatch<br/><small>Hong Kong fulfillment desk</small></div><div><ShieldCheck/>Made for daily use<br/><small>Durable materials, honest specs</small></div><div><RefreshCcw/>30-day returns<br/><small>Simple, transparent policy</small></div></section>
 <section className="catalog" id="catalog"><div className="catalog-head"><div><p className="eyebrow">THE CURRENT EDIT</p><h2>Objects for <i>living</i></h2></div><div className="filters"><button className={cat==='All'?'active':''} onClick={()=>setCat('All')}>All pieces</button>{categories.map(c=><button className={cat===c.name?'active':''} onClick={()=>setCat(c.name)} key={c.name}>{c.name}</button>)}</div></div><div className="grid">{visible.map(p=><ProductCard key={p.id} p={p} add={add} buy={buy}/>)}</div></section></main>
 <Footer setPage={setPage}/>{drawer&&<Cart cart={cart} close={()=>setDrawer(false)} checkout={()=>{setDrawer(false);setPage('checkout')}}/>}</>
}
function ProductCard({p,add,buy}){return <article className="product"><div className="product-image"><img src={p.image} alt={p.name}/><span>01/{String(p.id).padStart(2,'0')}</span></div><p className="product-cat">{p.category}</p><h3>{p.name}</h3><div className="product-bottom"><strong>${p.price}</strong><div><button onClick={()=>add(p)}>Add to Cart</button><button className="buy" onClick={()=>buy(p)}>Buy Now · ${p.price}</button></div></div></article>}
function Cart({cart,close,checkout}){let total=cart.reduce((s,p)=>s+p.price,0);return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">YOUR SELECTION</p><h2>Cart <small>{cart.length} pieces</small></h2></div><button onClick={close}><X/></button></div>{cart.length?<><div className="cart-items">{cart.map((p,i)=><div className="cart-item" key={`${p.id}-${i}`}><div className="mini-image"><img src={p.image} alt=""/></div><div><b>{p.name}</b><p>{p.category}</p></div><strong>${p.price}</strong></div>)}</div><div className="cart-total"><span>Subtotal</span><strong>${total}</strong></div><button className="checkout" onClick={checkout}>Continue to checkout <ArrowRight size={16}/></button><small className="demo-note">Demo checkout — payment is not captured.</small></>:<p className="empty">Your cart is ready for something useful.</p>}</aside></div>}
function Checkout({cart,onBack}){const total=cart.reduce((s,p)=>s+p.price,0);return <div className="simple-page"><div className="simple-top"><button onClick={onBack}>← Back to shop</button><span>SKYEYEHOME / CHECKOUT</span></div><div className="checkout-layout"><section><p className="eyebrow">ORDER DETAILS</p><h1>Make it yours.</h1>{cart.map((p,i)=><div className="checkout-item" key={`${p.id}-${i}`}><div className="mini-image"><img src={p.image} alt=""/></div><div><b>{p.name}</b><p>{p.category}</p></div><strong>${p.price}</strong></div>)}<div className="total"><span>Total</span><strong>${total}</strong></div></section><section className="pay-box"><p className="eyebrow">SECURE DEMO PAYMENT</p><h2>Payment method</h2><label className="pay-option"><input type="radio" defaultChecked name="pay"/> <span>PayPal</span><b>paypal</b></label><label className="pay-option"><input type="radio" name="pay"/> <span>Visa</span><b>VISA</b></label><label className="pay-option"><input type="radio" name="pay"/> <span>Credit / debit card</span><b>••••</b></label><button className="primary full" onClick={()=>alert('Demo order placed. No payment was captured.')}>Pay ${total} securely <ArrowRight size={16}/></button><p className="demo-note">This is a front-end demonstration. Connect a merchant account and server-side order service before launch.</p></section></div></div>}
function Info({onBack}){const [selected,setSelected]=useState(()=>{const key=decodeURIComponent(location.hash.split('policy=')[1]||'');return policyLabels.includes(key)?key:'About us'});return <div className="simple-page info"><div className="simple-top"><button onClick={onBack}>← Back to shop</button><span>SKYEYEHOME / INFORMATION</span></div><p className="eyebrow">POLICIES & COMPANY</p><h1>Clear, useful<br/><i>information.</i></h1><div className="policy-layout"><aside className="policy-nav">{policyLabels.map((x,i)=><button className={selected===x?'selected':''} onClick={()=>{setSelected(x);window.location.hash='policy='+encodeURIComponent(x)}} key={x}><span>0{i+1}</span>{x}</button>)}</aside><section className="policy-detail"><span className="eyebrow">{selected.toUpperCase()}</span><h2>{selected}</h2>{selected.startsWith('Terms')?<><p>These Terms of Service contain 17 sections governing use of {site.domain}, orders, payment, delivery, returns and legal responsibilities.</p><ol className="terms">{terms.map((t,i)=><li key={t}><b>{i+1}. {t}</b><p>Customers agree to use the site lawfully, review product details before ordering, and follow the instructions and responsibilities described for this topic.</p></li>)}</ol></>:<p className="policy-copy">{policyContent[selected]}</p>}<p className="policy-contact">Questions: <a href={'mailto:'+company.email}>{company.email}</a></p></section></div></div>}
function Admin({onBack}){const logout=()=>{localStorage.removeItem('skyeye-admin-auth');onBack()};return <div className="simple-page admin"><div className="simple-top"><button onClick={onBack}>← Back to shop</button><button onClick={logout}>Sign out</button><span>SKYEYEHOME / ADMIN DEMO</span></div><p className="eyebrow">STORE OPERATIONS</p><h1>Good morning,<br/><i>operator.</i></h1><div className="admin-box"><div><span>ORDERS TODAY</span><strong>08</strong></div><div><span>GROSS SALES</span><strong>$1,284</strong></div><div><span>LOW STOCK</span><strong>04</strong></div><p>Demo portal only. Production authentication and order APIs are not connected.</p></div></div>}
function AdminLogin({onBack,onLogin}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const submit=e=>{e.preventDefault();if(username===adminCredentials.username&&password===adminCredentials.password)onLogin();else setError('Incorrect demo credentials. Please try again.')};return <div className="simple-page admin-login"><div className="simple-top"><button onClick={onBack}>← Back to shop</button><span>SKYEYEHOME / ADMIN LOGIN</span></div><div className="login-card"><p className="eyebrow">PRIVATE STORE ACCESS</p><h1>Welcome<br/><i>back.</i></h1><form onSubmit={submit}><label>Email<input type="email" value={username} onChange={e=>setUsername(e.target.value)} placeholder="admin@skyeyehome.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" required/></label>{error&&<p className="login-error">{error}</p>}<button className="primary full" type="submit">Sign in <ArrowRight size={16}/></button></form><p className="demo-note">Demo login only. Connect server-side authentication before using this with real orders or customer data.</p></div></div>}
function Footer({setPage}){const openPolicy=x=>{window.location.hash='policy='+encodeURIComponent(x);setPage('info')};return <footer><div className="footer-top"><div><a className="logo">SKYEYE<span>HOME</span></a><p>Home goods for the shape of<br/>your everyday.</p></div><div><b>Shop</b>{categories.map(c=><a key={c.name}>{c.name}</a>)}</div><div><b>Information</b>{policyLabels.map(x=><a key={x} onClick={()=>openPolicy(x)}>{x}</a>)}<a onClick={()=>setPage('admin')}>Admin demo</a></div><div><b>Contact</b><p>Company Name: {company.name}</p><p>Email: {company.email}</p><p>Mobile number: {company.phone}</p><p>Address: {company.address}</p></div></div><div className="footer-bottom"><span>© 2026 {company.name}</span><span>{site.domain}</span><span>Registration no.: Not provided</span></div></footer>}
createRoot(document.getElementById('root')).render(<App/>)
